### ISSUE TITLE
missing 'ushort' internal type

### ISSUE THREAD

**Issue by noname77** [rogerbarton/sphinx-csharp#15]
hi,

got back to using this extension recently and im getting :

```
WARNING: Failed to find xref for: ushort, no objects found that end like this, searched in object types: ['class', 'struct', 'interface', 'enum']
```

and its indeed missing from the [built-in types](https://github.com/rogerbarton/sphinx-csharp/blob/master/sphinx_csharp/extrefs_data.py#L16)

will push a PR in a sec

best,
wiktor

**Comment by rogerbarton** [comment]
I also added all the other built-in types in the C# reference. I don't know why they weren't there from the beginning, thanks
